<a href="https://colab.research.google.com/github/AmishiR/ML-Lab/blob/main/Lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Credits=[3,3,1,2,2,1]
Grades=[10.0,8.0,9.0,8.0,9.0,10.0]
Tcredit=0
Total=0
for i in range(len(Credits)):
  Total= Credits[i]*Grades[i]+Total
  Tcredit=Credits[i]+Tcredit


Sgpa=Total/Tcredit
print(Sgpa)


8.916666666666666


In [ ]:
import numpy as np

In [ ]:
Credits=np.array(Credits)
Grades=np.array(Grades)
Temp=Credits*Grades
TCredits=np.sum(Credits)
Total=np.sum(Temp)
Sgpa=Total/Tcredit
print(Sgpa)


8.916666666666666


In [ ]:
Sgpa=np.sum(Credits*Grades)/np.sum(Credits)
print(Sgpa)

8.916666666666666


In [ ]:
Sgpa=np.dot(Credits,Grades)/np.sum(Credits)
print(Sgpa)

8.916666666666666


In [ ]:
#To check the shape of list or matrix
Credits.shape

(6,)

In [ ]:
Distance=np.array([200,300,400,500,600,700])
Time=np.array([10,30,10,25,30,70])
Speed=Distance/Time
print(Speed)

[20. 10. 40. 20. 20. 10.]


In [ ]:
X=[1,2,3]
print(X*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
X=np.array([1,2,3,4])
print(X*3)
print(X/2)

[ 3  6  9 12]
[0.5 1.  1.5 2. ]


In [ ]:
Y=np.arange(100,1,-3) #When step-size is known
Y

array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52,  49,  46,  43,  40,  37,  34,  31,  28,  25,
        22,  19,  16,  13,  10,   7,   4])

In [ ]:
X=np.arange(-10,50,2)
print(X)

[-10  -8  -6  -4  -2   0   2   4   6   8  10  12  14  16  18  20  22  24
  26  28  30  32  34  36  38  40  42  44  46  48]


In [ ]:
Y=np.linspace(1,100,10)
print(Y)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [ ]:
X=np.array([2,3,4,5,67,8,90])
print(X[-5:])

[ 4  5 67  8 90]


In [ ]:
print(np.sin(X))
print(np.tan(X))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.85551998  0.98935825
  0.89399666]
[-2.18503986 -0.14254654  1.15782128 -3.38051501  1.65231726 -6.79971146
 -1.99520041]


In [ ]:
Z=(np.log(X))
print(Z)
Z=np.exp(Z)  #calculate inverse
print(Z)

[0.69314718 1.09861229 1.38629436 1.60943791 4.20469262 2.07944154
 4.49980967]
[ 2.  3.  4.  5. 67.  8. 90.]


In [ ]:
X=np.arange(0,100,5)
X_smallest=np.min(X)
print(X_smallest)
X_largest =np.max(X)
print(X_largest)
X_mean=np.mean(X)
print(X_mean)
X_std=np.std(X)
print(X_std)
print(np.var(X))

0
95
47.5
28.83140648667699
831.25


Reshaping of an Array

In [ ]:
A=np.arange(1,20,2)
print(A)
print(len(A))

[ 1  3  5  7  9 11 13 15 17 19]
10


In [ ]:
A_reshaped=A.reshape(2,5)
print(A_reshaped)
print(A_reshaped.shape)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]
(2, 5)


In [ ]:
B=A_reshaped.reshape(1,10)
print(B)

[[ 1  3  5  7  9 11 13 15 17 19]]


In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
type(A)

numpy.ndarray

In [ ]:
A=np.matrix(A)
print(A)
type(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.matrix

In [ ]:
Z=np.zeros(shape=(2,2))
print(Z)
print(Z.size) #find no of elements in matrix
Z.shape[1]

[[0. 0.]
 [0. 0.]]
4


2

In [ ]:
A=np.zeros(shape=(3,5,4))
print(A)
print(A.shape)
print(A.shape[2])  #column

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(3, 5, 4)
4


In [ ]:
V=np.ones((2,2))
V

array([[1., 1.],
       [1., 1.]])

In [ ]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
I=np.eye(10)
I*-7
I=np.fliplr(I)
print(I)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
matrix=-9*np.ones(10)+2*np.eye(10)
print(matrix)

[[-7. -9. -9. -9. -9. -9. -9. -9. -9. -9.]
 [-9. -7. -9. -9. -9. -9. -9. -9. -9. -9.]
 [-9. -9. -7. -9. -9. -9. -9. -9. -9. -9.]
 [-9. -9. -9. -7. -9. -9. -9. -9. -9. -9.]
 [-9. -9. -9. -9. -7. -9. -9. -9. -9. -9.]
 [-9. -9. -9. -9. -9. -7. -9. -9. -9. -9.]
 [-9. -9. -9. -9. -9. -9. -7. -9. -9. -9.]
 [-9. -9. -9. -9. -9. -9. -9. -7. -9. -9.]
 [-9. -9. -9. -9. -9. -9. -9. -9. -7. -9.]
 [-9. -9. -9. -9. -9. -9. -9. -9. -9. -7.]]


In [ ]:
X=np.array([2,4,6,8,10,12,14,16,18,20])
Y=np.array([1,1,3,7,9,3,13,5,7,9])
Z=np.sum((X-Y)**2)
print(Z)

466


In [ ]:
  A=np.sum(I,axis=1)
  print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
